title: xf8b's Website
email: yesman58194@tutanota.com
description: bad website
baseurl: "/"
url: "https://xf8b.github.io" 
github_username: xf8b

markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
