title: xf8b's Website
email: unknownperson102424@pm.me
description: A website.
baseurl: "/"
url: "https://xf8b.github.io" 
github_username: xf8b

markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
